--- #YAML:1.0
name:               DBD-ADO
version:            2.99.2
abstract:           ADO driver for the DBI module.
author:
    - Tim Bunce, Phlip, Thomas Lowery and Steffen Goeldner ( http://dbi.perl.org )
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    DBI:         0
    Win32::OLE:  0.16
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
